logging:
    level:
        org:
            org:
                springframework: INFO

neo4j:
    uri: http://flight-advisor-lb-11685101.eu-central-1.elb.amazonaws.com:7474
    username: neo4j
jwt:
    authoritiesKey: role
    tokenValidity: 3600000