server:
    port: 8080
spring:
    flyway:
        baseline-on-migrate: true
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
        open-in-view: false
        show-sql: false
