logging:
    level:
        org:
            org:
                springframework: INFO

neo4j:
    uri: http://graph-database:7474
    username: neo4j
jwt:
    authoritiesKey: role
    tokenValidity: 3600000