logging:
    level:
        org:
            org:
                springframework: WARN

neo4j:
    uri: http://graph-database.htec-namespace:7474
    username: neo4j
jwt:
    authoritiesKey: role
    tokenValidity: 3600000