logging:
    level:
        org:
            org:
                springframework: INFO

neo4j:
    uri: bolt://graph-database:7687
    username: neo4j
jwt:
    authoritiesKey: role
    tokenValidity: 3600000