logging:
    level:
        org:
            org:
                springframework: DEBUG

neo4j:
#    uri: bolt://localhost:7687
    uri: http://flight-advisor-lb-11685101.eu-central-1.elb.amazonaws.com:7474
    username: neo4j
    password: secret
jwt:
    authoritiesKey: role
    tokenValidity: 10800000
    secret: Cg7i4cOUKJMmMtaCAsGIeZDloIcVcjRcaKuJTej2meUfZmSd1RuaYFuBWup5tDi
